version: 2
updates:
- package-ecosystem: maven
  directory: "/shoppingbackend"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework:spring-orm
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-core
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.27.Final
    - 5.4.28.Final
    - 5.4.29.Final
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.hibernate.validator:hibernate-validator
    versions:
    - 7.0.0.Final
